// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ffykgxnmijoonyutchzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmeWtneG5taWpvb255dXRjaHp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MDYxODcsImV4cCI6MjA2MDM4MjE4N30.tO2-3eJN1DlM_WubpMaIEpounF-9qzqOunRshUuMo8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);